name: neuralStyleTransfer
channels:
- conda-forge
- defaults
dependencies:
- python=3.6
- numpy
- pandas
- scipy
- jupyter
- scikit-learn
- flask
- conda-forge::keras
- conda-forge::tensorflow
- pip:
- ipykernel
- requests